apiVersion: v1
kind: Service
metadata:
  name: mamba-jamba-service
  namespace: my-namespace
  clusterName: my-cluster
  labels:
    app: mamba-jamba
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: mamba-jamba
